runtime: python311
env: flex
entrypoint: gunicorn --bind :$PORT --workers 4 --timeout 120 app:create_app()

automatic_scaling:
  min_instances: 1
  max_instances: 10

env_variables:
  FLASK_ENV: "production"
  
# Cloud SQL
# Database connection é feito via variáveis de ambiente
# DB_HOST: /cloudsql/PROJECT_ID:REGION:INSTANCE_NAME
# DB_USER: postgres
# DB_PASSWORD: (defina com uma senha segura)
# DB_NAME: adocao_gatos
